{
 "title": "Air Quality Control and Monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "roomStatus",
     "select": [
      [
       { "params": [ "roomstat" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 3 },
   "options": {
    "content": "<h1><p style=\"text-align: center; color: cyan\">LIVING ROOM</p></h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 3 },
   "options": {
    "content": "<h1><p style=\"text-align: center; color: red ;\">BEDROOM</p></h1>"
   }
  },
  {
   "title": "AIR QUALITY ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "airquality_v1_3",
     "select": [
      [
       { "params": [ "airquality" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "AIR QUALITY ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "airquality_v1_3",
     "select": [
      [
       { "params": [ "airquality" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dht11",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dht11",
     "select": [
      [
       { "params": [ "hum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "AIR QUALITY ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "airquality_v1_3",
     "select": [
      [
       { "params": [ "airquality" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "AIR QUALITY ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "airquality_v1_3",
     "select": [
      [
       { "params": [ "airquality" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dht11",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dht11",
     "select": [
      [
       { "params": [ "hum" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "SGP30 SENSOR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "ECO2",
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "eco2" ], "type": "field" },
       { "params": [ "ECO2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "ETHANOL",
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "ethanol" ], "type": "field" },
       { "params": [ "ETHANOL" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Hydrogen",
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "hydrogen" ], "type": "field" },
       { "params": [ "ETHANOL" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "TVOC",
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "tvoc" ], "type": "field" },
       { "params": [ "ETHANOL" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "SGP30 SENSOR",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "ECO2",
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "eco2" ], "type": "field" },
       { "params": [ "ECO2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "ETHANOL",
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "ethanol" ], "type": "field" },
       { "params": [ "ETHANOL" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Hydrogen",
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "hydrogen" ], "type": "field" },
       { "params": [ "ETHANOL" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "TVOC",
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "tvoc" ], "type": "field" },
       { "params": [ "ETHANOL" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Heat intensity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dht11",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "DUST SENSOR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 12 },
   "targets": [
    {
     "measurement": "dust",
     "select": [
      [
       { "params": [ "concentration" ], "type": "field" },
       { "params": [ "concentration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Heat intensity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "dht11",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "DUST SENSOR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "targets": [
    {
     "measurement": "dust",
     "select": [
      [
       { "params": [ "concentration" ], "type": "field" },
       { "params": [ "concentration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Eco2",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "ECO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "eco2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Hydrogen",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "targets": [
    {
     "alias": "Hydrogen Room 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "hydrogen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Ventilator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "ventilator" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Heater",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "heater" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "airPurifier",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "airPurifier" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Eco2",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "targets": [
    {
     "alias": "ECO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "eco2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Hydrogen",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "targets": [
    {
     "alias": "Hydrogen Room 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "hydrogen" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Ventilator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "ventilator" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Heater",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "heater" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "airPurifier",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "airPurifier" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "SGP 30",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "tvoc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tVOC" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Ethanol",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
   "targets": [
    {
     "alias": "ETHANOL ROOM 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "ethanol" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Air Coditioner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "airConditioner" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Humidifier",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "humidifier" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Ethanol",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 22 },
   "targets": [
    {
     "alias": "ETHANOL ROOM 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "ethanol" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "SGP 30",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sgp30",
     "select": [
      [
       { "params": [ "tvoc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tVOC" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Air Coditioner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "airConditioner" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Humidifier",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "actuatorStatus",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VentilatorStatus" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "actuator", "operator": "=", "value": "humidifier" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "2" }
     ]
    }
   ]
  }
 ]
}